apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      run: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        run: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: sqreept/ssh-server:latest
        volumeMounts:
        - name: ssh-authorized-keys-volume
          mountPath: /root/.ssh/
          readOnly: true
      volumes:
      - name: ssh-authorized-keys-volume
        configMap:
          name: ssh-authorized-keys
          items:
          - key: authorized_keys
            path: authorized_keys
            mode: 384
          defaultMode: 448
