apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    run: {{ .Chart.Name }}
